USE [FireArc]
GO

/****** Object:  Index [STARFIRE_INCIDENT_ID]    Script Date: 16/05/2023 12:31:34 ******/
CREATE CLUSTERED INDEX [STARFIRE_INCIDENT_ID] ON [dbo].[Fire_Incident_Dispatch_Data]
(
	[starfire_incident_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


